<?php
/**
 * Title: FAQ — Accordion Style
 * Slug: rezon8-25-material/faq-accordion
 * Categories: faq
 * Description: FAQ using Details/Summary blocks in accordion style.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","contentSize":"800px"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Frequently Asked Questions</h2><!-- /wp:heading -->
<!-- wp:details {"style":{"border":{"bottom":{"color":"#e0e0e0","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}}} --><details class="wp-block-details" style="border-bottom:1px solid #e0e0e0;padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)"><summary style="font-weight:500;cursor:pointer">How long does it take to see results?</summary><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"spacing":{"margin":{"top":"var:preset|spacing|20"}}}} --><p class="has-text-color" style="color:#6d7174;margin-top:var(--wp--preset--spacing--20)">Most clients begin seeing measurable improvements within 60–90 days. Paid advertising can show results in weeks, while SEO and organic strategies typically mature over 3–6 months. We'll set realistic expectations during onboarding.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details {"style":{"border":{"bottom":{"color":"#e0e0e0","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}}} --><details class="wp-block-details" style="border-bottom:1px solid #e0e0e0;padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)"><summary style="font-weight:500;cursor:pointer">Do you require long-term contracts?</summary><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"spacing":{"margin":{"top":"var:preset|spacing|20"}}}} --><p class="has-text-color" style="color:#6d7174;margin-top:var(--wp--preset--spacing--20)">No. All our plans are month-to-month. We believe in earning your business every month through results. We do offer discounts for annual commitments, but there's never a cancellation penalty.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details {"style":{"border":{"bottom":{"color":"#e0e0e0","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}}} --><details class="wp-block-details" style="border-bottom:1px solid #e0e0e0;padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)"><summary style="font-weight:500;cursor:pointer">What industries do you work with?</summary><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"spacing":{"margin":{"top":"var:preset|spacing|20"}}}} --><p class="has-text-color" style="color:#6d7174;margin-top:var(--wp--preset--spacing--20)">We work across a wide range of industries including retail, healthcare, legal, home services, restaurants, real estate, automotive, and professional services. Our team has deep expertise in local and regional B2C marketing.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details {"style":{"border":{"bottom":{"color":"#e0e0e0","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}}} --><details class="wp-block-details" style="border-bottom:1px solid #e0e0e0;padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)"><summary style="font-weight:500;cursor:pointer">How is performance tracked and reported?</summary><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"spacing":{"margin":{"top":"var:preset|spacing|20"}}}} --><p class="has-text-color" style="color:#6d7174;margin-top:var(--wp--preset--spacing--20)">You'll receive a comprehensive monthly performance report covering all active channels. We also provide a real-time dashboard so you can check in anytime. We track leads, revenue attribution, traffic, conversions, and ad spend ROI.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}}} --><details class="wp-block-details" style="padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)"><summary style="font-weight:500;cursor:pointer">What's included in the onboarding process?</summary><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"spacing":{"margin":{"top":"var:preset|spacing|20"}}}} --><p class="has-text-color" style="color:#6d7174;margin-top:var(--wp--preset--spacing--20)">Onboarding typically takes 2 weeks and includes a kick-off call, business and brand audit, competitive analysis, strategy presentation, and access setup. You'll have a clear 90-day roadmap before we launch anything.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
</div><!-- /wp:group -->
