<?php
/**
 * Title: FAQ — Two Column Layout
 * Slug: rezon8-25-material/faq-two-col
 * Categories: faq
 * Description: FAQs in a two-column card layout.
 */
?>
<!-- wp:group {"align":"full","style":{"color":{"background":"#f5f5f5"},"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","wideSize":"1100px"}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#f5f5f5;padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Got Questions?</h2><!-- /wp:heading -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}}} --><div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column">
<!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"},"margin":{"bottom":"var:preset|spacing|30"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--40);margin-bottom:var(--wp--preset--spacing--30)"><!-- wp:heading {"level":5,"style":{"color":{"text":"#0d0d0d"},"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h5 class="wp-block-heading has-text-color" style="color:#0d0d0d;font-weight:500;font-size:1rem">Do I need a big budget to get started?</h5><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Our Starter plan begins at $297/month — designed to deliver real value for businesses with modest marketing budgets.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--40)"><!-- wp:heading {"level":5,"style":{"color":{"text":"#0d0d0d"},"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h5 class="wp-block-heading has-text-color" style="color:#0d0d0d;font-weight:500;font-size:1rem">Will I own the content you create?</h5><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Yes — all content, creative assets, and campaign data belong to you. We never hold your assets hostage.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
</div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column">
<!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"},"margin":{"bottom":"var:preset|spacing|30"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--40);margin-bottom:var(--wp--preset--spacing--30)"><!-- wp:heading {"level":5,"style":{"color":{"text":"#0d0d0d"},"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h5 class="wp-block-heading has-text-color" style="color:#0d0d0d;font-weight:500;font-size:1rem">Can I upgrade or downgrade my plan?</h5><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Absolutely. Your plan can change month to month based on your business needs. We'll recommend changes when it makes sense for your growth.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
<!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--40)"><!-- wp:heading {"level":5,"style":{"color":{"text":"#0d0d0d"},"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h5 class="wp-block-heading has-text-color" style="color:#0d0d0d;font-weight:500;font-size:1rem">How do I get started?</h5><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Book a free 30-minute strategy call. We'll review your goals, ask smart questions, and tell you exactly what we'd recommend — no pressure.</p><!-- /wp:paragraph --></div><!-- /wp:group -->
</div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
