<?php
/**
 * Title: FAQ — Dark Accordion
 * Slug: rezon8-25-material/faq-dark-accordion
 * Categories: faq
 * Description: Dark background FAQ section with accordion style.
 */
?>
<!-- wp:group {"align":"full","style":{"color":{"background":"#0d0d0d"},"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","contentSize":"800px"}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#0d0d0d;padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"#ffffff"},"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center has-text-color" style="color:#ffffff;font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Common Questions</h2><!-- /wp:heading -->
<!-- wp:details {"style":{"color":{"text":"rgba(255,255,255,0.85)"},"border":{"bottom":{"color":"rgba(255,255,255,0.1)","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}}} --><details class="wp-block-details has-text-color" style="color:rgba(255,255,255,0.85);border-bottom:1px solid rgba(255,255,255,0.1);padding:var(--wp--preset--spacing--30) 0"><summary style="font-weight:500;color:#ffffff;cursor:pointer">What makes Rezon8 different from other agencies?</summary><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.6)"},"spacing":{"margin":{"top":"var:preset|spacing|20"}}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.6);margin-top:var(--wp--preset--spacing--20)">We combine strategy, creativity, and technology in a way that most agencies can't. We're not a vendor — we're a long-term growth partner who knows your business and is invested in your success.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details {"style":{"color":{"text":"rgba(255,255,255,0.85)"},"border":{"bottom":{"color":"rgba(255,255,255,0.1)","width":"1px"}},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}}} --><details class="wp-block-details has-text-color" style="color:rgba(255,255,255,0.85);border-bottom:1px solid rgba(255,255,255,0.1);padding:var(--wp--preset--spacing--30) 0"><summary style="font-weight:500;color:#ffffff;cursor:pointer">Do you handle ad spend, or is that extra?</summary><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.6)"},"spacing":{"margin":{"top":"var:preset|spacing|20"}}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.6);margin-top:var(--wp--preset--spacing--20)">Ad spend (media budget) is separate from our management fees. We'll help you determine the right budget for your goals and platforms, and you'll always have direct visibility into how your budget is being used.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
<!-- wp:details {"style":{"color":{"text":"rgba(255,255,255,0.85)"},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}}} --><details class="wp-block-details has-text-color" style="color:rgba(255,255,255,0.85);padding:var(--wp--preset--spacing--30) 0"><summary style="font-weight:500;color:#ffffff;cursor:pointer">How involved do I need to be?</summary><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.6)"},"spacing":{"margin":{"top":"var:preset|spacing|20"}}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.6);margin-top:var(--wp--preset--spacing--20)">As much or as little as you want. Some clients are hands-on; others prefer to approve and let us run. We adapt to your preference and keep you informed without overwhelming you.</p><!-- /wp:paragraph --></details><!-- /wp:details -->
</div><!-- /wp:group -->
