<?php
/**
 * Title: Features — 3-Column with Icons
 * Slug: rezon8-25-material/features-3col-icons
 * Categories: features
 * Description: Three feature columns with emoji icons, headline, and description.
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","wideSize":"1200px"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:group {"layout":{"type":"constrained","contentSize":"600px"},"style":{"spacing":{"blockGap":"var:preset|spacing|20","margin":{"bottom":"var:preset|spacing|60"}}}} --><div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--60)"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.75rem","fontWeight":"700","letterSpacing":"0.15em","textTransform":"uppercase"}}} --><p class="has-text-align-center has-text-color" style="color:#11c6de;font-size:0.75rem;font-weight:700;letter-spacing:0.15em;text-transform:uppercase">What We Do</p><!-- /wp:paragraph --><!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300">A Complete Marketing Partner</h2><!-- /wp:heading --></div><!-- /wp:group -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"}}}} --><div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"style":{"typography":{"fontSize":"2.5rem","lineHeight":"1"},"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}}} --><p style="font-size:2.5rem;line-height:1;margin-bottom:var(--wp--preset--spacing--30)">📡</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h3 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Digital Marketing Strategy</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.9rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.9rem">Data-driven strategies tailored to your market, audience, and growth goals. We build the plan, then execute it.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"style":{"typography":{"fontSize":"2.5rem","lineHeight":"1"},"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}}} --><p style="font-size:2.5rem;line-height:1;margin-bottom:var(--wp--preset--spacing--30)">🎬</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h3 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Content Creation</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.9rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.9rem">Professional video, photography, copywriting, and social content that captures attention and drives engagement.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"style":{"typography":{"fontSize":"2.5rem","lineHeight":"1"},"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}}} --><p style="font-size:2.5rem;line-height:1;margin-bottom:var(--wp--preset--spacing--30)">🎯</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h3 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Paid Advertising</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.9rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.9rem">Google Ads, Meta, YouTube, and programmatic campaigns optimized for your cost-per-acquisition goals.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"},"margin":{"top":"var:preset|spacing|50"}}}} --><div class="wp-block-columns" style="margin-top:var(--wp--preset--spacing--50)">
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"style":{"typography":{"fontSize":"2.5rem","lineHeight":"1"},"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}}} --><p style="font-size:2.5rem;line-height:1;margin-bottom:var(--wp--preset--spacing--30)">🔍</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h3 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">SEO &amp; Local Search</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.9rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.9rem">Dominate search results in your market with technical SEO, local optimization, and content strategy.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"style":{"typography":{"fontSize":"2.5rem","lineHeight":"1"},"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}}} --><p style="font-size:2.5rem;line-height:1;margin-bottom:var(--wp--preset--spacing--30)">✉️</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h3 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Email &amp; Automation</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.9rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.9rem">Nurture leads, retain customers, and grow revenue with smart email sequences and marketing automation.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:paragraph {"style":{"typography":{"fontSize":"2.5rem","lineHeight":"1"},"spacing":{"margin":{"bottom":"var:preset|spacing|30"}}}} --><p style="font-size:2.5rem;line-height:1;margin-bottom:var(--wp--preset--spacing--30)">📊</p><!-- /wp:paragraph --><!-- wp:heading {"level":3,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h3 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Analytics &amp; Reporting</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.9rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.9rem">Real-time dashboards and monthly reports that translate data into clear business decisions.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
