<?php
/**
 * Title: Features — Numbered Steps
 * Slug: rezon8-25-material/features-numbered
 * Categories: features
 * Description: Feature list with large numbered steps and descriptions.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","contentSize":"800px"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">How We Work</h2><!-- /wp:heading -->
<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"flex-start"},"style":{"spacing":{"blockGap":"var:preset|spacing|40","margin":{"bottom":"var:preset|spacing|40"}}}} --><div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"level":3,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"3rem","fontWeight":"300","lineHeight":"1"}}} --><h3 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:3rem;font-weight:300;line-height:1">01</h3><!-- /wp:heading --><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} --><div class="wp-block-group"><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Discovery &amp; Audit</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"}}} --><p class="has-text-color" style="color:#6d7174">We dive deep into your business, brand, and competitive landscape to understand where you are and where you want to go.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"flex-start"},"style":{"spacing":{"blockGap":"var:preset|spacing|40","margin":{"bottom":"var:preset|spacing|40"}}}} --><div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"level":3,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"3rem","fontWeight":"300","lineHeight":"1"}}} --><h3 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:3rem;font-weight:300;line-height:1">02</h3><!-- /wp:heading --><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} --><div class="wp-block-group"><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Strategy &amp; Roadmap</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"}}} --><p class="has-text-color" style="color:#6d7174">We build a 90-day marketing roadmap with clear milestones, KPIs, and channel mix designed for your specific goals.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"flex-start"},"style":{"spacing":{"blockGap":"var:preset|spacing|40","margin":{"bottom":"var:preset|spacing|40"}}}} --><div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"level":3,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"3rem","fontWeight":"300","lineHeight":"1"}}} --><h3 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:3rem;font-weight:300;line-height:1">03</h3><!-- /wp:heading --><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} --><div class="wp-block-group"><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Launch &amp; Execute</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"}}} --><p class="has-text-color" style="color:#6d7174">We deploy your campaigns, content, and systems — then continuously test and optimize to improve performance month over month.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"flex-start"},"style":{"spacing":{"blockGap":"var:preset|spacing|40"}}} --><div class="wp-block-group"><!-- wp:heading {"level":3,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"3rem","fontWeight":"300","lineHeight":"1"}}} --><h3 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:3rem;font-weight:300;line-height:1">04</h3><!-- /wp:heading --><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|10"}}} --><div class="wp-block-group"><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1.125rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:1.125rem">Report &amp; Scale</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"}}} --><p class="has-text-color" style="color:#6d7174">Monthly performance reviews, transparent reporting, and strategic pivots to keep your growth on track as your business evolves.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
</div><!-- /wp:group -->
