<?php
/**
 * Title: Features — Cards on Dark
 * Slug: rezon8-25-material/features-cards-dark
 * Categories: features
 * Description: Feature cards on a dark background with brand accent borders.
 */
?>
<!-- wp:group {"align":"full","style":{"color":{"background":"#0d0d0d"},"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","wideSize":"1200px"}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#0d0d0d;padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"#ffffff"},"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center has-text-color" style="color:#ffffff;font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Our Core Services</h2><!-- /wp:heading -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}}} --><div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#1a1a1a"},"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}},"border":{"top":{"color":"#11c6de","width":"3px"}}}} --><div class="wp-block-group has-background" style="background-color:#1a1a1a;padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40);border-top:3px solid #11c6de"><!-- wp:paragraph style="font-size:2rem" --><p style="font-size:2rem">📡</p><!-- /wp:paragraph --><!-- wp:heading {"level":4,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"1rem","fontWeight":"500"}}} --><h4 class="wp-block-heading has-text-color" style="color:#ffffff;font-size:1rem;font-weight:500">Brand Strategy</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.6)"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.6);font-size:0.875rem">Positioning, messaging, and identity systems that make your brand unmistakable.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#1a1a1a"},"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}},"border":{"top":{"color":"#11c6de","width":"3px"}}}} --><div class="wp-block-group has-background" style="background-color:#1a1a1a;padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40);border-top:3px solid #11c6de"><!-- wp:paragraph style="font-size:2rem" --><p style="font-size:2rem">📣</p><!-- /wp:paragraph --><!-- wp:heading {"level":4,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"1rem","fontWeight":"500"}}} --><h4 class="wp-block-heading has-text-color" style="color:#ffffff;font-size:1rem;font-weight:500">Social Media</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.6)"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.6);font-size:0.875rem">Content creation, community management, and paid social campaigns that grow your audience.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#1a1a1a"},"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}},"border":{"top":{"color":"#11c6de","width":"3px"}}}} --><div class="wp-block-group has-background" style="background-color:#1a1a1a;padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40);border-top:3px solid #11c6de"><!-- wp:paragraph style="font-size:2rem" --><p style="font-size:2rem">🌐</p><!-- /wp:paragraph --><!-- wp:heading {"level":4,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"1rem","fontWeight":"500"}}} --><h4 class="wp-block-heading has-text-color" style="color:#ffffff;font-size:1rem;font-weight:500">Web &amp; SEO</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.6)"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.6);font-size:0.875rem">High-converting websites and search optimization strategies that bring qualified traffic.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#1a1a1a"},"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}},"border":{"top":{"color":"#11c6de","width":"3px"}}}} --><div class="wp-block-group has-background" style="background-color:#1a1a1a;padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40);border-top:3px solid #11c6de"><!-- wp:paragraph style="font-size:2rem" --><p style="font-size:2rem">⚡</p><!-- /wp:paragraph --><!-- wp:heading {"level":4,"style":{"color":{"text":"#ffffff"},"typography":{"fontSize":"1rem","fontWeight":"500"}}} --><h4 class="wp-block-heading has-text-color" style="color:#ffffff;font-size:1rem;font-weight:500">Automation</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.6)"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.6);font-size:0.875rem">CRM setup, email sequences, and workflow automation that nurture leads while you sleep.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
