<?php
/**
 * Title: Features — Alternating Rows
 * Slug: rezon8-25-material/features-alternating
 * Categories: features
 * Description: Alternating image-and-text rows for a deep feature breakdown.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","wideSize":"1100px"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|60"},"margin":{"bottom":"var:preset|spacing|70"}}}} --><div class="wp-block-columns are-vertically-aligned-center" style="margin-bottom:var(--wp--preset--spacing--70)"><!-- wp:column {"width":"45%"} --><div class="wp-block-column" style="flex-basis:45%"><!-- wp:image {"sizeSlug":"r8-card","style":{"border":{"radius":"12px"}}} --><figure class="wp-block-image size-r8-card" style="border-radius:12px"><img src="https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=700&q=80" alt="Strategy" style="border-radius:12px"/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column {"width":"55%"} --><div class="wp-block-column" style="flex-basis:55%"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Strategy that's built around your business</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"}}} --><p class="has-text-color" style="color:#6d7174">We start every engagement with a deep-dive audit of your market, competitors, and current performance. No generic plans — just what works for you.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|60"},"margin":{"bottom":"var:preset|spacing|70"}}}} --><div class="wp-block-columns are-vertically-aligned-center" style="margin-bottom:var(--wp--preset--spacing--70)"><!-- wp:column {"width":"55%"} --><div class="wp-block-column" style="flex-basis:55%"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Content that converts, not just impresses</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"}}} --><p class="has-text-color" style="color:#6d7174">Every piece of content we create — video, copy, or design — is engineered to move your audience toward a specific action that grows your business.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column {"width":"45%"} --><div class="wp-block-column" style="flex-basis:45%"><!-- wp:image {"sizeSlug":"r8-card","style":{"border":{"radius":"12px"}}} --><figure class="wp-block-image size-r8-card" style="border-radius:12px"><img src="https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=700&q=80" alt="Content" style="border-radius:12px"/></figure><!-- /wp:image --></div><!-- /wp:column --></div><!-- /wp:columns -->
<!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|60"}}}} --><div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"width":"45%"} --><div class="wp-block-column" style="flex-basis:45%"><!-- wp:image {"sizeSlug":"r8-card","style":{"border":{"radius":"12px"}}} --><figure class="wp-block-image size-r8-card" style="border-radius:12px"><img src="https://images.unsplash.com/photo-1543286386-713bdd548da4?w=700&q=80" alt="Analytics" style="border-radius:12px"/></figure><!-- /wp:image --></div><!-- /wp:column --><!-- wp:column {"width":"55%"} --><div class="wp-block-column" style="flex-basis:55%"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Data that tells a clear story</h3><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"}}} --><p class="has-text-color" style="color:#6d7174">Our reporting doesn't bury you in vanity metrics. You get a clear view of what's working, what isn't, and what we're doing about it.</p><!-- /wp:paragraph --></div><!-- /wp:column --></div><!-- /wp:columns -->
</div><!-- /wp:group -->
