<?php
/**
 * Title: Features — Badge Capability Grid
 * Slug: rezon8-25-material/features-badge-grid
 * Categories: features
 * Description: Grid of capability chips/badges showing service breadth.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|50"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--50)">Our Full Capability Set</h2><!-- /wp:heading -->
<!-- wp:group {"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"center"},"style":{"spacing":{"blockGap":"var:preset|spacing|20"}}} --><div class="wp-block-group">
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">SEO Strategy</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Google Ads</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Meta Advertising</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Email Marketing</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Video Production</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Social Media</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Brand Identity</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Copywriting</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">CRM Setup</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Web Design</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">PR &amp; Media</p><!-- /wp:paragraph -->
<!-- wp:paragraph {"style":{"color":{"background":"#e0f7fa","text":"#006494"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"20px","right":"20px"}},"border":{"radius":"9999px"},"typography":{"fontSize":"0.875rem","fontWeight":"500"}}} --><p class="has-text-color has-background" style="background-color:#e0f7fa;color:#006494;border-radius:9999px;padding:8px 20px;font-size:0.875rem;font-weight:500">Analytics</p><!-- /wp:paragraph -->
</div><!-- /wp:group -->
</div><!-- /wp:group -->
