<?php
/**
 * Title: Plans — Monthly/Annual Toggle Layout
 * Slug: rezon8-25-material/plans-toggle
 * Categories: query
 * Description: Plan cards with note about annual savings.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","wideSize":"1100px"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:group {"layout":{"type":"constrained","contentSize":"600px"},"style":{"spacing":{"blockGap":"var:preset|spacing|20","margin":{"bottom":"var:preset|spacing|50"}}}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--50)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300">Invest in Growth</h2><!-- /wp:heading -->
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#6d7174"}}} --><p class="has-text-align-center has-text-color" style="color:#6d7174">All plans billed monthly. <strong style="color:#11c6de">Save 20%</strong> when billed annually. No long-term contracts required.</p><!-- /wp:paragraph -->
</div><!-- /wp:group -->
<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|30"}}}} -->
<div class="wp-block-columns alignwide">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-plan-card"} --><div class="wp-block-group r8-plan-card" style="padding:2.5rem 1.5rem"><!-- wp:heading {"level":4,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.7rem","fontWeight":"700","letterSpacing":"0.15em","textTransform":"uppercase"}}} --><h4 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:0.7rem;font-weight:700;letter-spacing:0.15em;text-transform:uppercase">Starter</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"2rem","fontWeight":"300"}}} --><p class="has-text-color" style="color:#11c6de;font-size:2rem;font-weight:300">$297<span style="font-size:1rem;color:#6d7174">/mo</span></p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.8rem">or $238/mo billed annually</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline","width":100} --><div class="wp-block-button is-style-outline has-custom-width wp-block-button__width-100"><a class="wp-block-button__link wp-element-button" href="/contact?plan=starter">Get Started</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-plan-card is-featured","style":{"color":{"background":"#0d0d0d"}}} --><div class="wp-block-group r8-plan-card is-featured has-background" style="background-color:#0d0d0d;padding:2.5rem 1.5rem"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.65rem","fontWeight":"700","letterSpacing":"0.15em","textTransform":"uppercase"}}} --><p class="has-text-align-center has-text-color" style="color:#11c6de;font-size:0.65rem;font-weight:700;letter-spacing:0.15em;text-transform:uppercase">Most Popular</p><!-- /wp:paragraph --><!-- wp:heading {"level":4,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.7rem","fontWeight":"700","letterSpacing":"0.15em","textTransform":"uppercase"}}} --><h4 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:0.7rem;font-weight:700;letter-spacing:0.15em;text-transform:uppercase">Growth</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"2rem","fontWeight":"300"}}} --><p class="has-text-color" style="color:#11c6de;font-size:2rem;font-weight:300">$697<span style="font-size:1rem;color:rgba(255,255,255,0.5)">/mo</span></p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.5)"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.5);font-size:0.8rem">or $558/mo billed annually</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"width":100} --><div class="wp-block-button has-custom-width wp-block-button__width-100"><a class="wp-block-button__link wp-element-button" href="/contact?plan=growth">Get Started</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-plan-card"} --><div class="wp-block-group r8-plan-card" style="padding:2.5rem 1.5rem"><!-- wp:heading {"level":4,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.7rem","fontWeight":"700","letterSpacing":"0.15em","textTransform":"uppercase"}}} --><h4 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:0.7rem;font-weight:700;letter-spacing:0.15em;text-transform:uppercase">Authority</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"2rem","fontWeight":"300"}}} --><p class="has-text-color" style="color:#11c6de;font-size:2rem;font-weight:300">$1,497<span style="font-size:1rem;color:#6d7174">/mo</span></p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.8rem">or $1,198/mo billed annually</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline","width":100} --><div class="wp-block-button is-style-outline has-custom-width wp-block-button__width-100"><a class="wp-block-button__link wp-element-button" href="/contact?plan=authority">Get Started</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
