<?php
/**
 * Title: Process — Horizontal Timeline
 * Slug: rezon8-25-material/process-timeline
 * Categories: process
 * Description: 4-step horizontal process timeline.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Our Process</h2><!-- /wp:heading -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|30"}}}} --><div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column" style="text-align:center"><!-- wp:paragraph {"align":"center","style":{"color":{"background":"#11c6de","text":"#ffffff"},"spacing":{"padding":{"top":"16px","bottom":"16px","left":"16px","right":"16px"}},"border":{"radius":"50%"},"layout":{"selfStretch":"fixed","flexSize":"56px"}}} --><p class="has-text-color has-background" style="background-color:#11c6de;color:#ffffff;border-radius:50%;width:56px;height:56px;line-height:56px;font-weight:700;font-size:1.2rem;margin:0 auto">1</p><!-- /wp:paragraph --><!-- wp:heading {"level":5,"textAlign":"center","style":{"typography":{"fontWeight":"500"},"spacing":{"margin":{"top":"var:preset|spacing|30"}}}} --><h5 class="wp-block-heading has-text-align-center" style="font-weight:500;margin-top:var(--wp--preset--spacing--30)">Discover</h5><!-- /wp:heading --><!-- wp:paragraph {"align":"center","style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-align-center has-text-color" style="color:#6d7174;font-size:0.875rem">Deep-dive audit of your brand, market, and competitors.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column" style="text-align:center"><!-- wp:paragraph {"align":"center","style":{"color":{"background":"#11c6de","text":"#ffffff"},"spacing":{"padding":{"top":"16px","bottom":"16px","left":"16px","right":"16px"}},"border":{"radius":"50%"}}} --><p class="has-text-color has-background" style="background-color:#11c6de;color:#ffffff;border-radius:50%;width:56px;height:56px;line-height:56px;font-weight:700;font-size:1.2rem;margin:0 auto">2</p><!-- /wp:paragraph --><!-- wp:heading {"level":5,"textAlign":"center","style":{"typography":{"fontWeight":"500"},"spacing":{"margin":{"top":"var:preset|spacing|30"}}}} --><h5 class="wp-block-heading has-text-align-center" style="font-weight:500;margin-top:var(--wp--preset--spacing--30)">Strategize</h5><!-- /wp:heading --><!-- wp:paragraph {"align":"center","style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-align-center has-text-color" style="color:#6d7174;font-size:0.875rem">90-day roadmap with KPIs, channels, and milestones.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column" style="text-align:center"><!-- wp:paragraph {"align":"center","style":{"color":{"background":"#11c6de","text":"#ffffff"},"spacing":{"padding":{"top":"16px","bottom":"16px","left":"16px","right":"16px"}},"border":{"radius":"50%"}}} --><p class="has-text-color has-background" style="background-color:#11c6de;color:#ffffff;border-radius:50%;width:56px;height:56px;line-height:56px;font-weight:700;font-size:1.2rem;margin:0 auto">3</p><!-- /wp:paragraph --><!-- wp:heading {"level":5,"textAlign":"center","style":{"typography":{"fontWeight":"500"},"spacing":{"margin":{"top":"var:preset|spacing|30"}}}} --><h5 class="wp-block-heading has-text-align-center" style="font-weight:500;margin-top:var(--wp--preset--spacing--30)">Execute</h5><!-- /wp:heading --><!-- wp:paragraph {"align":"center","style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-align-center has-text-color" style="color:#6d7174;font-size:0.875rem">Launch, test, optimize — continuous improvement every week.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column" style="text-align:center"><!-- wp:paragraph {"align":"center","style":{"color":{"background":"#11c6de","text":"#ffffff"},"spacing":{"padding":{"top":"16px","bottom":"16px","left":"16px","right":"16px"}},"border":{"radius":"50%"}}} --><p class="has-text-color has-background" style="background-color:#11c6de;color:#ffffff;border-radius:50%;width:56px;height:56px;line-height:56px;font-weight:700;font-size:1.2rem;margin:0 auto">4</p><!-- /wp:paragraph --><!-- wp:heading {"level":5,"textAlign":"center","style":{"typography":{"fontWeight":"500"},"spacing":{"margin":{"top":"var:preset|spacing|30"}}}} --><h5 class="wp-block-heading has-text-align-center" style="font-weight:500;margin-top:var(--wp--preset--spacing--30)">Scale</h5><!-- /wp:heading --><!-- wp:paragraph {"align":"center","style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-align-center has-text-color" style="color:#6d7174;font-size:0.875rem">Monthly reviews, reporting, and strategic pivots for growth.</p><!-- /wp:paragraph --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
