<?php
/**
 * Title: Services — Icon Grid
 * Slug: rezon8-25-material/services-grid
 * Categories: services
 * Description: Service cards in a 3-column grid.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","wideSize":"1200px"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Services We Offer</h2><!-- /wp:heading -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}}} --><div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:paragraph style="font-size:2rem" --><p style="font-size:2rem">🔍</p><!-- /wp:paragraph --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h4 style="font-weight:500;font-size:1rem">Search Engine Optimization</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Get found by people actively searching for what you offer. Local, national, and technical SEO services.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="/services/seo" style="color:#11c6de;font-size:0.875rem;font-weight:500">Learn more →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:paragraph style="font-size:2rem" --><p style="font-size:2rem">🎯</p><!-- /wp:paragraph --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h4 style="font-weight:500;font-size:1rem">Paid Advertising</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Targeted Google, Meta, and YouTube campaigns engineered for measurable ROI and customer acquisition.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="/services/paid-ads" style="color:#11c6de;font-size:0.875rem;font-weight:500">Learn more →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:paragraph style="font-size:2rem" --><p style="font-size:2rem">🎬</p><!-- /wp:paragraph --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h4 style="font-weight:500;font-size:1rem">Video &amp; Content</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Professional video production, photography, and copywriting that captures attention and builds trust.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="/services/content" style="color:#11c6de;font-size:0.875rem;font-weight:500">Learn more →</a></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
