<?php
/**
 * Title: Stats — Light Background Cards
 * Slug: rezon8-25-material/stats-light-cards
 * Categories: stats
 * Description: Individual metric cards on light grey surface.
 */
?>
<!-- wp:group {"align":"full","style":{"color":{"background":"#f5f5f5"},"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#f5f5f5;padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}}} --><div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:heading {"level":2,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"2.5rem","fontWeight":"300"}}} --><h2 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:2.5rem;font-weight:300">300+</h2><!-- /wp:heading --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"0.9rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:0.9rem">Clients Served</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.8rem">Across retail, healthcare, professional services, and more.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:heading {"level":2,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"2.5rem","fontWeight":"300"}}} --><h2 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:2.5rem;font-weight:300">$2M+</h2><!-- /wp:heading --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"0.9rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:0.9rem">Revenue Generated</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.8rem">In measurable client revenue tied to our campaigns.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:heading {"level":2,"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"2.5rem","fontWeight":"300"}}} --><h2 class="wp-block-heading has-text-color" style="color:#11c6de;font-size:2.5rem;font-weight:300">98%</h2><!-- /wp:heading --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"0.9rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:0.9rem">Retention Rate</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.8rem">Clients stay because we consistently deliver results.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
