<?php
/**
 * Title: Team — Team Grid 3col
 * Slug: rezon8-25-material/team-grid-3col
 * Categories: team
 * Description: Team section layout — team-grid-3col.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Meet the Team</h2><!-- /wp:heading -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}}} --><div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:image {"sizeSlug":"r8-thumb","style":{"border":{"radius":"50%"},"layout":{"selfStretch":"fixed","flexSize":"80px"}}} --><figure class="wp-block-image size-r8-thumb" style="border-radius:50%"><img src="https://i.pravatar.cc/160?img=11" alt="Team member" style="border-radius:50%;width:80px;height:80px;object-fit:cover"/></figure><!-- /wp:image --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:1rem">Marcus Williams</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.8rem","fontWeight":"500"}}} --><p class="has-text-color" style="color:#11c6de;font-size:0.8rem;font-weight:500">Founder &amp; CEO</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">10+ years in digital marketing and brand strategy across Metro Detroit and beyond.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:image {"sizeSlug":"r8-thumb","style":{"border":{"radius":"50%"}}} --><figure class="wp-block-image size-r8-thumb" style="border-radius:50%"><img src="https://i.pravatar.cc/160?img=5" alt="Team member" style="border-radius:50%;width:80px;height:80px;object-fit:cover"/></figure><!-- /wp:image --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:1rem">Jasmine Carter</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.8rem","fontWeight":"500"}}} --><p class="has-text-color" style="color:#11c6de;font-size:0.8rem;font-weight:500">Creative Director</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Award-winning designer and video producer with a passion for storytelling that converts.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:image {"sizeSlug":"r8-thumb","style":{"border":{"radius":"50%"}}} --><figure class="wp-block-image size-r8-thumb" style="border-radius:50%"><img src="https://i.pravatar.cc/160?img=33" alt="Team member" style="border-radius:50%;width:80px;height:80px;object-fit:cover"/></figure><!-- /wp:image --><!-- wp:heading {"level":4,"style":{"typography":{"fontWeight":"500","fontSize":"1rem"}}} --><h4 class="wp-block-heading" style="font-weight:500;font-size:1rem">Derek Okafor</h4><!-- /wp:heading --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.8rem","fontWeight":"500"}}} --><p class="has-text-color" style="color:#11c6de;font-size:0.8rem;font-weight:500">Head of Paid Media</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem">Google and Meta certified. Managed over M in ad spend with consistent positive ROI for clients.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
