<?php
/**
 * Title: Testimonials — Stacked with Avatar
 * Slug: rezon8-25-material/testimonials-stacked
 * Categories: testimonials
 * Description: Vertically stacked testimonials with avatar placeholder.
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","contentSize":"700px"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Success Stories</h2><!-- /wp:heading -->
<!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"},"margin":{"bottom":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50);margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"1.25rem"}}} --><p class="has-text-color" style="color:#11c6de;font-size:1.25rem">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>"From zero social presence to 12,000 followers and consistent inbound leads every week. Rezon8 delivered beyond expectations."</p><!-- /wp:paragraph --><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"center"},"style":{"spacing":{"blockGap":"var:preset|spacing|30","margin":{"top":"var:preset|spacing|30"}}}} --><div class="wp-block-group" style="margin-top:var(--wp--preset--spacing--30)"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontWeight":"700","fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#11c6de;font-weight:700;font-size:0.875rem">Robert Kim · <span style="color:#6d7174;font-weight:400">Kim &amp; Associates Law</span></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50","right":"var:preset|spacing|50"},"margin":{"bottom":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50);margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"1.25rem"}}} --><p class="has-text-color" style="color:#11c6de;font-size:1.25rem">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>"We were skeptical at first, but three months in, our revenue from digital channels doubled. Worth every penny."</p><!-- /wp:paragraph --><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"center"},"style":{"spacing":{"blockGap":"var:preset|spacing|30","margin":{"top":"var:preset|spacing|30"}}}} --><div class="wp-block-group" style="margin-top:var(--wp--preset--spacing--30)"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontWeight":"700","fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#11c6de;font-weight:700;font-size:0.875rem">Dena Powell · <span style="color:#6d7174;font-weight:400">Powell Catering Co.</span></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group -->
</div><!-- /wp:group -->
