<?php
/**
 * Title: Testimonials — Dark Background
 * Slug: rezon8-25-material/testimonials-dark-bg
 * Categories: testimonials
 * Description: Two testimonials side by side on a dark background.
 */
?>
<!-- wp:group {"align":"full","style":{"color":{"background":"#0d0d0d"},"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","wideSize":"1100px"}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#0d0d0d;padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"#ffffff"},"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center has-text-color" style="color:#ffffff;font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Trusted by Growing Businesses</h2><!-- /wp:heading -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#1a1a1a"},"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}},"border":{"left":{"color":"#11c6de","width":"4px"}}}} --><div class="wp-block-group has-background" style="background-color:#1a1a1a;padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40);border-left:4px solid #11c6de"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"1.25rem"}}} --><p class="has-text-color" style="color:#11c6de;font-size:1.25rem">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.85)"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.85)">"Rezon8 helped us go from invisible online to dominating our local market. The ROI speaks for itself."</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontWeight":"700","fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#11c6de;font-weight:700;font-size:0.875rem">Kevin Moore</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.4)"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.4);font-size:0.8rem">Owner, Moore's HVAC</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#1a1a1a"},"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}},"border":{"left":{"color":"#11c6de","width":"4px"}}}} --><div class="wp-block-group has-background" style="background-color:#1a1a1a;padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40);border-left:4px solid #11c6de"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"1.25rem"}}} --><p class="has-text-color" style="color:#11c6de;font-size:1.25rem">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.85)"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.85)">"We've tried other agencies and none came close. Rezon8 is the real deal — strategic, creative, and accountable."</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontWeight":"700","fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#11c6de;font-weight:700;font-size:0.875rem">Angela Torres</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"rgba(255,255,255,0.4)"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:rgba(255,255,255,0.4);font-size:0.8rem">Director, Torres Dental</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
