<?php
/**
 * Title: Testimonials — Logo + Quote
 * Slug: rezon8-25-material/testimonials-logo-quote
 * Categories: testimonials
 * Description: Testimonials with company logo placeholder and inline quote.
 */
?>
<!-- wp:group {"align":"full","style":{"color":{"background":"#fafafa"},"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#fafafa;padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"},"spacing":{"margin":{"bottom":"var:preset|spacing|60"}}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300;margin-bottom:var(--wp--preset--spacing--60)">Trusted Across Industries</h2><!-- /wp:heading -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}}} -->
<div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card-outlined","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card-outlined" style="padding:var(--wp--preset--spacing--40)"><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem","fontStyle":"italic"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem;font-style:italic">"Game-changing results."</p><!-- /wp:paragraph --><!-- wp:separator {"style":{"color":{"background":"#e0e0e0"}}} --><hr class="wp-block-separator has-alpha-channel-opacity has-background" style="background-color:#e0e0e0"/><!-- /wp:separator --><!-- wp:paragraph {"style":{"color":{"text":"#231f20"},"typography":{"fontWeight":"700","fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#231f20;font-weight:700;font-size:0.8rem">Retail Industry</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card-outlined","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card-outlined" style="padding:var(--wp--preset--spacing--40)"><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem","fontStyle":"italic"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem;font-style:italic">"Doubled our leads in 90 days."</p><!-- /wp:paragraph --><!-- wp:separator {"style":{"color":{"background":"#e0e0e0"}}} --><hr class="wp-block-separator has-alpha-channel-opacity has-background" style="background-color:#e0e0e0"/><!-- /wp:separator --><!-- wp:paragraph {"style":{"color":{"text":"#231f20"},"typography":{"fontWeight":"700","fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#231f20;font-weight:700;font-size:0.8rem">Healthcare Industry</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card-outlined","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card-outlined" style="padding:var(--wp--preset--spacing--40)"><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.875rem","fontStyle":"italic"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.875rem;font-style:italic">"Best agency we've worked with."</p><!-- /wp:paragraph --><!-- wp:separator {"style":{"color":{"background":"#e0e0e0"}}} --><hr class="wp-block-separator has-alpha-channel-opacity has-background" style="background-color:#e0e0e0"/><!-- /wp:separator --><!-- wp:paragraph {"style":{"color":{"text":"#231f20"},"typography":{"fontWeight":"700","fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#231f20;font-weight:700;font-size:0.8rem">Professional Services</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
