<?php
/**
 * Title: Testimonials — 3-Column Grid
 * Slug: rezon8-25-material/testimonials-grid
 * Categories: testimonials
 * Description: Three testimonial cards in a grid layout.
 */
?>
<!-- wp:group {"align":"full","style":{"color":{"background":"#f5f5f5"},"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"layout":{"type":"constrained","wideSize":"1200px"}} -->
<div class="wp-block-group alignfull has-background" style="background-color:#f5f5f5;padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)">
<!-- wp:group {"layout":{"type":"constrained","contentSize":"600px"},"style":{"spacing":{"blockGap":"var:preset|spacing|20","margin":{"bottom":"var:preset|spacing|60"}}}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--60)">
<!-- wp:paragraph {"align":"center","style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"0.75rem","fontWeight":"700","letterSpacing":"0.15em","textTransform":"uppercase"}}} --><p class="has-text-align-center has-text-color" style="color:#11c6de;font-size:0.75rem;font-weight:700;letter-spacing:0.15em;text-transform:uppercase">Client Reviews</p><!-- /wp:paragraph -->
<!-- wp:heading {"textAlign":"center","style":{"typography":{"fontWeight":"300"}}} --><h2 class="wp-block-heading has-text-align-center" style="font-weight:300">What Our Clients Say</h2><!-- /wp:heading -->
</div><!-- /wp:group -->
<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}}} -->
<div class="wp-block-columns">
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"1.5rem"}}} --><p class="has-text-color" style="color:#11c6de;font-size:1.5rem">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#231f20"}}} --><p class="has-text-color" style="color:#231f20">"Rezon8 completely transformed our online presence. Within 3 months we saw a 40% increase in qualified leads."</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontWeight":"700","fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#11c6de;font-weight:700;font-size:0.875rem">Sarah Mitchell</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.8rem">CEO, Brightfield Solutions</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"1.5rem"}}} --><p class="has-text-color" style="color:#11c6de;font-size:1.5rem">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#231f20"}}} --><p class="has-text-color" style="color:#231f20">"The team at Rezon8 is exceptional. They took the time to really understand our business and built a strategy that works."</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontWeight":"700","fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#11c6de;font-weight:700;font-size:0.875rem">Marcus Johnson</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.8rem">Owner, Detroit Auto Works</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
<!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"r8-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|40","right":"var:preset|spacing|40"}}}} --><div class="wp-block-group r8-card" style="padding:var(--wp--preset--spacing--50) var(--wp--preset--spacing--40)"><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontSize":"1.5rem"}}} --><p class="has-text-color" style="color:#11c6de;font-size:1.5rem">★★★★★</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#231f20"}}} --><p class="has-text-color" style="color:#231f20">"Best investment we've made. Our social following grew 300% and our in-store traffic doubled in 6 months."</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#11c6de"},"typography":{"fontWeight":"700","fontSize":"0.875rem"}}} --><p class="has-text-color" style="color:#11c6de;font-weight:700;font-size:0.875rem">Lisa Tran</p><!-- /wp:paragraph --><!-- wp:paragraph {"style":{"color":{"text":"#6d7174"},"typography":{"fontSize":"0.8rem"}}} --><p class="has-text-color" style="color:#6d7174;font-size:0.8rem">Founder, Bloom Boutique</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column -->
</div><!-- /wp:columns -->
</div><!-- /wp:group -->
